Repository GSG-G13/autocomplete-ahmed-shatha, pull requests merged in 2023-03, with the labels that each got.

#3 Create File Structure
  package-lock.json
  package.json
  public/css/stylesheet.css
  public/index.html
  public/js/index.js
  src/data.json
  src/server.js
  tests/routes.test.js
Labels: approve

#5 create html css
  public/css/stylesheet.css
  public/index.html
Labels: approve

#12 create modal
  public/css/stylesheet.css
  public/index.html
Labels: closed, frontend

#10 Create utils
  src/utils.js
Labels: high priority, backend, Abstraction

#13 7 edit fetch method
  public/index.html
  public/js/fetch.js
Labels: approve, API

#16 edit html css
  public/css/stylesheet.css
  public/index.html
  public/js/index.js
  src/data.json
Labels: backend, frontend

#17 create router
  public/index.html
  src/router.js
  src/utils.js
Labels: backend, waiting review

#20 19 create search
  package.json
  public/css/stylesheet.css
  public/index.html
  public/js/index.js
  src/router.js
  src/search.js
  src/server.js
  src/utils.js
  tests/routes.test.js
Labels: approve

#23 create search
  README.md
  public/js/index.js
Labels: approve
